### PR TITLE
client: Fix server stream reading

### LINKED ISSUE #149: pool: search objects works only for local node
When we try to find objects that are not located on the requested node we find nothing 

Logs:
```
2022-02-24T07:41:30.610Z	debug	search/search.go:27	serving request...	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false}
2022-02-24T07:41:30.612Z	debug	search/search.go:43	operation finished successfully	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false}
2022-02-24T07:41:30.613Z	debug	search/container.go:18	trying to execute in container...	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false, "netmap lookup depth": 0}
2022-02-24T07:41:30.614Z	debug	search/container.go:49	process epoch	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false, "number": 1178}
2022-02-24T07:41:30.614Z	debug	search/remote.go:11	processing node...	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false}
2022-02-24T07:41:30.615Z	debug	search/remote.go:21	local operation failed	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false, "error": "reading the response failed: rpc error: code = Canceled desc = context canceled"}
2022-02-24T07:41:30.615Z	debug	search/container.go:71	interrupt placement iteration by context	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false, "error": "context canceled"}
2022-02-24T07:41:30.615Z	debug	search/search.go:43	operation finished successfully	{"component": "Object.Get service", "request": "SEARCH", "container": "5hEiVVUGNDe8LtbZRe1BxjTQuxXAqVgRWq2mNabm58CX", "local": false, "with session": true, "with bearer": false}
```

@cthulhu-rider found the problem in https://github.com/nspcc-dev/neofs-sdk-go/blob/master/client/object_search.go#L148-L151 but there is some problem in api (there is not native `EOF`)

### PR DESCRIPTION
**Pull request by cthulhu-rider**
* closes #149

### CODE REVIEW

File: client/object_search.go [hunk 1]
```diff
@@ -136,33 +136,41 @@ func (x *ObjectListReader) Read(buf []oid.ID) (int, bool) {
...
+		for i = 0; i < ln; i++ {
+			buf[read+i] = *oid.NewIDFromV2(ids[i]) // need smth better
+		}
 
-	read += ln
+		read += ln
 
-	// save the tail
-	x.tail = append(x.tail, ids[ln:]...)
+		// save the tail and break
```
Comment (fyrchik) [inline client/object_search.go]: >_>

**Review by fyrchik — APPROVED** [review]

**Review by KirillovDenis — APPROVED** [review]
