### PR TITLE
fix/Do not return EOF while streaming payload

### LINKED ISSUE #496: Handle io.EOF during object writes
See nspcc-dev/neofs-node#2518, SDK should return a real error right from the `Write()` call, then `Close()` is a no-op returning `nil`. All streaming interfaces should be checked for this.

### PR DESCRIPTION
**Pull request by carpawell**
If EOF is returned on `Write` call, close the stream, try to unwrap status and return it immediately as `error` instead of direct `io.EOF`. Closes #496.

### CODE REVIEW

**Comment by carpawell** [comment]
> then `Close()` is a no-op returning `nil`

@roman-khimov, @smallhive, @cthulhu-rider, let's discuss it. PR does return closing error instead of `nil`. Not sure what is a better idea.

**Comment by carpawell** [comment]
Also, `Put` is the only client side stream, so others are OK.

File: client/object_put.go [hunk 1]
```diff
@@ -222,6 +232,11 @@ func (x *DefaultObjectWriter) Close() error {
 
 	defer x.cancelCtxStream()
 
+	if x.streamClosed {
+		err = x.err
+		return x.closeErr
```
Comment (roman-khimov) [inline client/object_put.go:237]: `return nil`

**Review by roman-khimov — CHANGES_REQUESTED** [review]
There has to be a test for it.

File: client/object_put.go (hunk 1 above)
Comment (carpawell) [reply client/object_put.go:237]: so closing stream error is ignored _always_, right?

Comment (roman-khimov) [reply client/object_put.go:237]: We're closing the connection, do we have any issue with closing it? No -> no error. If there was some error _before_ the connection was closed, it had been returned to the user already.

File: client/object_put.go [hunk 2]
```diff
@@ -222,6 +232,11 @@ func (x *DefaultObjectWriter) Close() error {
 
 	defer x.cancelCtxStream()
 
+	if x.streamClosed {
+		err = x.err
```
Comment (roman-khimov) [inline client/object_put.go:236]: BTW, this can lead to counting the error twice, which isn't what we want. Likely no statistics should be collected at all (and context cancelling can be done in `Write()` itself.

File: client/object_put.go (hunk 1 above)
Comment (smallhive) [reply client/object_put.go:237]: I tend to agree with `return nil`, because you got `EOF` during the object uploading and you in the middle of this process. You have just one way - to close the connection. Even it is an error, it doesn't matter - previous one is more important

File: client/object_put.go (hunk 2 above)
Comment (carpawell) [reply client/object_put.go:236]: @smallhive, statistics is not smth i understand what for, so can you, please answer whether logical errors should be passed to that handler?

File: client/object_put.go (hunk 1 above)
Comment (carpawell) [reply client/object_put.go:237]: > do we have any issue with closing it?

nobody can say for sure, that is an external library that returns an `error`

Comment (carpawell) [reply client/object_put.go]: updated the code, look, please and suggest your ideas

File: client/object_put.go (hunk 2 above)
Comment (carpawell) [reply client/object_put.go]: or... i finally got you. anyway, recheck, please

File: client/object_put.go [hunk 3]
```diff
@@ -186,6 +187,15 @@ func (x *DefaultObjectWriter) Write(chunk []byte) (n int, err error) {
 
 		x.err = x.stream.Write(&x.req)
 		if x.err != nil {
+			if errors.Is(x.err, io.EOF) {
+				_ = x.stream.Close()
+				x.err = x.client.processResponse(&x.respV2)
+				x.streamClosed = true
+				x.cancelCtxStream()
+
+				return writtenBytes, x.err
```
Comment (roman-khimov) [inline client/object_put.go:196]: The same line as the one below.

**Comment by carpawell** [comment]
> There has to be a test for it.

Added.

**Review by smallhive — APPROVED** [review]
