### PR TITLE
policy: Remove error listeners from query lexer

### LINKED ISSUE #280: Unwanted output in placement policy decode
The following code:
```
var result netmap.PlacementPolicy

err := result.DecodeString("{\"replicas\":[{\"count\":3,\"selector\":\"SelASD0\"}],\"container_backup_factor\":3,\"selectors\":[{\"name\":\"SelASD0\",\"count\":3,\"filter\":\"*\"}],\"filters\":[]}")
if err != nil {
	fmt.Println(err)
}
```

produce output:
```
line 1:0 token recognition error at: '{'
line 1:11 token recognition error at: ':'
line 1:12 token recognition error at: '['
line 1:13 token recognition error at: '{'
line 1:21 token recognition error at: ':'
line 1:23 token recognition error at: ','
line 1:34 token recognition error at: ':'
line 1:44 token recognition error at: '}'
line 1:45 token recognition error at: ']'
line 1:46 token recognition error at: ','
line 1:72 token recognition error at: ':'
line 1:74 token recognition error at: ','
line 1:86 token recognition error at: ':'
line 1:87 token recognition error at: '['
line 1:88 token recognition error at: '{'
line 1:95 token recognition error at: ':'
line 1:105 token recognition error at: ','
line 1:113 token recognition error at: ':'
line 1:115 token recognition error at: ','
line 1:124 token recognition error at: ':'
line 1:128 token recognition error at: '}'
line 1:129 token recognition error at: ']'
line 1:130 token recognition error at: ','
line 1:140 token recognition error at: ':'
line 1:141 token recognition error at: '['
line 1:142 token recognition error at: ']'
line 1:143 token recognition error at: '}'
policy: syntax error: line 1:1 mismatched input '"replicas"' expecting 'REP'
```

Though `err` contains only `policy: syntax error: line 1:1 mismatched input '"replicas"' expecting 'REP'`

Related https://github.com/nspcc-dev/neofs-s3-gw/issues/557

### PR DESCRIPTION
**Pull request by cthulhu-rider**
In previous implementation `PlacementPolicy.DecodeString` produced
undesired console logs.

Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>

* closes #280

### CODE REVIEW

**Review by KirillovDenis — APPROVED** [review]

File: netmap/policy.go [hunk 1]
```diff
@@ -553,6 +553,7 @@ func writeFilterStringTo(w io.StringWriter, f netmap.Filter) error {
 func (p *PlacementPolicy) DecodeString(s string) error {
 	input := antlr.NewInputStream(s)
 	lexer := parser.NewQueryLexer(input)
+	lexer.RemoveErrorListeners()
```
Comment (fyrchik) [inline netmap/policy.go:556]: See https://github.com/nspcc-dev/neofs-sdk-go/issues/280#issuecomment-1168287995
Can we reuse existing error listener instead?

Comment (cthulhu-rider) [reply netmap/policy.go:558]: @fyrchik pls check it out did I understand u correctly 4486898aab30039edff0d1f585a87cffb2a4ab0f

Comment (fyrchik) [reply netmap/policy.go:558]: Yes, exactly. Could you also add a test that `?REP 1` fails to be parsed?

**Review by fyrchik — APPROVED** [review]
