### PR TITLE
Fix/Clarify expiration epoch

### LINKED ISSUE #370: `EXPIRATION_EPOCH` must be the last "available" epoch for all entities
All the entities must be considered valid at `EXPIRATION_EPOCH`. At least the session is wrong:
https://github.com/nspcc-dev/neofs-sdk-go/blob/a690dcb159177f3036f9567cda4b30778ec2c0b0/session/common.go#L260-L262

### PR DESCRIPTION
**Pull request by carpawell**
The expiration epoch is the _last_ valid epoch for an entity. Also, clarify 
the expiration epoch meaning for tombstones and regular objects.

Signed-off-by: Pavel Karpy <p.karpy@yadro.com>

Closes #370.

### CODE REVIEW

File: object/tombstone.go [hunk 1]
```diff
@@ -33,12 +33,18 @@ func (t *Tombstone) ToV2() *tombstone.Tombstone {
 	return (*tombstone.Tombstone)(t)
 }
 
-// ExpirationEpoch return number of tombstone expiration epoch.
+// ExpirationEpoch returns the last NeoFS epoch
+// number of the tombstone lifetime.
```
Comment (fyrchik) [inline object/tombstone.go:37]: Do you think `epoch number` is better than just `epoch`?

**Review by fyrchik — APPROVED** [review]

File: object/tombstone.go (hunk 1 above)
Comment (carpawell) [reply object/tombstone.go:37]: took that naming from another comment, do not remember exactly where from
